export const workSamples = [
  {
    id: 1,
    siteName: 'Yomogi Diner App',
    description: 'Japanese flashcard app',
    longDescription:
      "A food-order app that I build for my girlfriend's birthday. It actually emails me orders!",
    href: 'https://hiraganaflashcards.netlify.app/',
    skills: [
      'TypeScript',
      'TailwindCSS',
      'Next.js',
      'Node.js',
      'Original Design',
    ],
    imagePath: '/img/portfolio/yomogi.png',
    alt: 'placeholder',
  },
  {
    id: 2,
    siteName: 'Hiragana',
    description: 'Japanese flashcard app',
    longDescription:
      'An open-source flashcard app I designed and built to help myself and others learn Japanese kanji',
    href: 'https://hiraganaflashcards.netlify.app/',
    skills: ['React', 'CSS', 'Original Design'],
    imagePath: '/img/portfolio/hiragana-flashcards.png',
    alt: 'placeholder',
  },
  {
    id: 3,
    siteName: 'La Mountains',
    description: 'recipe database app',
    longDescription:
      'Adventure tourism page for a fictional company, built for a job application skills test.',
    href: 'https://forkify-morgan-oshaughnessey-v2.netlify.app/',
    skills: ['JavaScript', 'React'],
    imagePath: '/img/portfolio/la-mountains.png',
    alt: 'placeholder',
  },
  {
    id: 4,
    siteName: 'Bids Picker',
    description: 'minimalist banking app',
    longDescription:
      'A quick little project I created to answer a skills test for a job application.',
    href: 'https://bankist-app-morgan-oshaughnessey.netlify.app/',
    skills: ['JavaScript', 'React'],
    imagePath: '/img/portfolio/bids-picker.png',
    alt: 'placeholder',
  },
  {
    id: 5,
    siteName: 'Omnifood',
    description: 'AI meal plan service',
    longDescription:
      'Advertisement page for a fictional AI-powered food delivery service. A pixel-perfect design built with vanilla HTML and CSS',
    href: 'https://omnifood-morgan-oshaughnessey.netlify.app/',
    skills: ['HTML', 'CSS'],
    imagePath: '/img/portfolio/omnifood.png',
    alt: 'placeholder',
  },
  {
    id: 6,
    siteName: 'Converse Adds',
    description: 'minimalist banking app',
    longDescription:
      'A class project building add templates in basic HTML and CSS',
    href: 'https://bankist-app-morgan-oshaughnessey.netlify.app/',
    skills: ['HTML', 'CSS'],
    imagePath: '/img/portfolio/converse-add.png',
    alt: 'placeholder',
  },
  {
    id: 7,
    siteName: 'Forkify',
    description: 'recipe database app',
    longDescription:
      'Recipe app with automatic portion adjustments and bookmarking features. Powered by an API with over 1 million recipes.',
    href: 'https://forkify-morgan-oshaughnessey-v2.netlify.app/',
    skills: ['JavaScript'],
    imagePath: '/img/portfolio/forkify.png',
    alt: 'placeholder',
  },
  {
    id: 8,
    siteName: 'Mapty',
    description: 'excercise logging app',
    longDescription:
      'An exercise-logging app that stores data locally on your computer and is easy to use.',
    href: 'https://mapty-portfolio-app.netlify.app/',
    skills: ['JavaScript'],
    imagePath: '/img/portfolio/mapty.png',
    alt: 'placeholder',
  },
  {
    id: 9,
    siteName: 'Bankist: Login Page',
    description: 'minimalist banking app',
    longDescription:
      'A beautiful landing page for a banking app built using pure JavaScript.',
    href: 'https://bankist-app-morgan-oshaughnessey.netlify.app/',
    skills: ['JavaScript'],
    imagePath: '/img/portfolio/bankist-login.png',
    alt: 'placeholder',
  },
  {
    id: 10,
    siteName: 'Bankist: app',
    description: 'minimalist banking app',
    longDescription:
      'A deep study in array methods from an amazing course by Jonas Schmedtmann',
    href: 'https://bankist-login-morgan-oshaughnessey.netlify.app',
    skills: ['JavaScript'],
    imagePath: '/img/portfolio/bankist-app.png',
    alt: 'Minimalist banking app, white background with green, yellow, and red interface to complete financial transations.',
  },
  {
    id: 11,
    siteName: 'Pig Game',
    description: 'Dice-rolling game',
    longDescription: 'A 2-player dice-rolling game, built with pure Javscript!',
    href: 'https://bankist-app-morgan-oshaughnessey.netlify.app/',
    skills: ['JavaScript'],
    imagePath: '/img/portfolio/pig-game.png',
    alt: 'Dice rolling game, styled in pink and red, first player to 100 wins.',
  },
  {
    id: 12,
    siteName: 'Guess My Number',
    description: 'Number guessing game',
    longDescription:
      'An early class project, lots of interesting logic behind the scenes!',
    href: 'https://guess-my-number-morgan-oshaughnessey.netlify.app/',
    skills: ['JavaScript'],
    imagePath: '/img/portfolio/guess-my-number.png',
    alt: 'number-guessing app',
  },
  {
    id: 13,
    siteName: 'Music Player',
    description: 'A platform for my musical compositions',
    longDescription:
      'My very first app! A platform for my musical compositions. Built with loving and patient help from my girlfriend.',
    href: 'https://moshalto.com/',
    skills: ['JavaScript', 'React'],
    imagePath: '/img/portfolio/music-player.png',
    alt: 'moshalto.com website image, a music player styled to look like a rubiks cube',
  },
];
