export const workSamples = [
  {
    id: 17,
    opusNumber: '',
    siteName: 'KLiC.gg',
    subtitle: 'A video multi-streaming platform',
    aboutText:
      'Contract work for a small startup, I currently serve as their front end technical lead.',
    cardText:
      'Led a team of 3 developers in a platform-wide refactor, improving site performance by 89%',
    href: '/',
    skills: ['TypeScript', 'Next.js', 'GraphQL', 'Agile Methodologies'],
    imagePath: '/img/portfolio/klic-homepage.png',
    alt: 'landing page for KLiC site',
  },
  {
    id: 16,
    opusNumber: '',
    siteName: 'A Poem A Day',
    subtitle: 'Poetry Platform for Stephen Harlow Berman',
    aboutText:
      'Far from finished and still, this website was an honor to design and build. It was my most complex project to date, despite the simple UI. I wrote custom scripts to transform 742 .pages files to .txt and then .md, adding custom metadata that was extracted dynamically. Fun project, super rewarding!',
    cardText:
      'A poem a day since 21 August, 2020. Currently under constuction, this is an early MVP demo.',
    href: 'https://berman-poems.vercel.app/',
    skills: [
      'TypeScript',
      'TailwindCSS',
      'Next.js',
      'Node.js',
      'Original Design',
      'Agile Methodologies',
    ],
    imagePath: '/img/portfolio/berman-poems.png',
    alt: 'An elegant poetry platform featuring elegant serif font on parchement',
  },
  {
    id: 15,
    opusNumber: '',
    siteName: 'IkeGPT',
    subtitle: 'Hawaiian culturally-aligned chatbot',
    aboutText:
      'An interactive AI chatbot interface that proposes responses incorporating Hawaiian values, enabling users to refine and submit suggestions for enhanced cultural alignment and community engagement',
    cardText:
      'An interactive AI chatbot interface that proposes responses incorporating Hawaiian values, enabling users to refine and submit suggestions for enhanced cultural alignment and community engagement',
    href: 'https://olelotools.com/ikegpt',
    skills: [
      'TypeScript',
      'TailwindCSS',
      'Next.js',
      'Node.js',
      'Original Design',
      'Agile Methodologies',
    ],
    imagePath: '/img/portfolio/ike-gpt.png',
    alt: 'Web page for Olelotools IkeGPT Hawaiian culturally-aligned chatbot',
  },
  {
    id: 14,
    opusNumber: '',
    siteName: 'Son Rise Child Care',
    subtitle: 'Small Business Website',
    aboutText:
      'This was such a fun and cute project to put together! The business owner and head teacher is super amazing, she is a force for good in this world.',
    cardText:
      'The official home of Son Rise Child Care, serving South Seattle for 37 years!',
    href: 'https://www.sonrisechildcare.com/',
    skills: ['Custom WIX Design', 'Agile Methodologies'],
    imagePath: '/img/portfolio/son-rise.png',
    alt: 'Fun, colorful, relaxing homepage for a daycare center',
  },
  {
    id: 13,
    opusNumber: '',
    siteName: 'Yomogi Diner App',
    subtitle: 'Food ordering app',
    aboutText:
      'This is one of my longest-running and most-improved projects! It started off as a totally ugly, unstyled, non-functional class project. I did all of the styling, mobile optimizations, backend middleware, and even built a custom kanban board for the kitchen!',
    cardText:
      "A food-order app that I built for my girlfriend's birthday. It actually emails me orders!",
    href: 'https://yomogi-nine.vercel.app/',
    skills: [
      'TypeScript',
      'TailwindCSS',
      'Next.js',
      'Node.js',
      'Original Design',
      'Agile Methodologies',
    ],
    imagePath: '/img/portfolio/yomogi.png',
    alt: 'A bright, colorful green and purple food order app',
  },
  {
    id: 12,
    opusNumber: '',
    siteName: 'Hiragana',
    subtitle: 'Japanese flashcard app',
    aboutText: 'I actually used this quite a bit to help me learn Japanese!',
    cardText:
      'An open-source flashcard app I designed and built to help myself and others learn Japanese kanji',
    href: 'https://hiraganaflashcards.netlify.app/',
    skills: ['React', 'CSS', 'Original Design'],
    imagePath: '/img/portfolio/hiragana-flashcards.png',
    alt: 'Japanese flashcard app with watercolor paintings of rivers and mountains in the background',
  },
  {
    id: 11,
    opusNumber: '',
    siteName: 'La Mountains',
    subtitle: 'Mountaineering Events Company',
    aboutText:
      "They said 'build this in one hour' and gave me a photoshop design file. I took three days, and built it in React. Didn't get the job, this was an ass-kicker of a skills test but I learned SO much from it, and it really propelled me forward. I'm proud of it. Not going to go back and edit it, it needs to remain as a pure snapshot in time.",
    cardText:
      'Adventure tourism page for a fictional company, built for a job application skills test.',
    href: 'https://la-mountains-morgan-oshaughnessey.netlify.app/',
    skills: ['JavaScript', 'React'],
    imagePath: '/img/portfolio/la-mountains.png',
    alt: 'Home page for a mountain touring company in Los Angeles',
  },
  {
    id: 10,
    opusNumber: '',
    siteName: 'Bids Picker',
    subtitle: 'Demo skills test app',
    aboutText:
      "Follow-up to a skills test I took on a job application. I didn't know Python, but I solved it in JavaScript and built this little cute demo app that matched the test prompt (create a bidding app for a business client to save them time on pricing optimizations)",
    cardText:
      'A quick little project I created to answer a skills test for a job application.',
    href: 'https://bid-picker.netlify.app/',
    skills: ['JavaScript', 'React'],
    imagePath: '/img/portfolio/bids-picker.png',
    alt: 'Small demo app that sorts bids and picks the three highest',
  },
  {
    id: 9,
    opusNumber: '',
    siteName: 'Omnifood',
    subtitle: 'AI meal plan service',
    aboutText:
      'Man, this app is a MONUMENT to the power of vanilla html and css. I aboslutely loved this course by Jonas Schmedtmann, and would highly recommend it.',
    cardText:
      'Advertisement page for a fictional AI-powered food delivery service. A pixel-perfect design built with vanilla HTML and CSS',
    href: 'https://omnifood-morgan-oshaughnessey.netlify.app/',
    skills: ['HTML', 'CSS'],
    imagePath: '/img/portfolio/omnifood.png',
    alt: 'Home page for a fictional AI-powered food delivery service',
  },
  {
    id: 8,
    opusNumber: '',
    siteName: 'Converse Ads',
    subtitle: 'Collection of faux Converse ads.',
    aboutText: 'A very satisfying set of small studies in CSS',
    cardText: 'A class project building add templates in basic HTML and CSS',
    href: 'https://codepen.io/collection/GoQVpQ',
    skills: ['HTML', 'CSS'],
    imagePath: '/img/portfolio/converse-add.png',
    alt: 'Collection of Converse shoe ads',
  },
  {
    id: 7,
    opusNumber: '',
    siteName: 'Forkify',
    subtitle: 'recipe database app',
    aboutText: 'My first real api-call app!',
    cardText:
      'Recipe app with automatic portion adjustments and bookmarking features. Powered by an API with over 1 million recipes.',
    href: 'https://forkify-morgan-oshaughnessey-v2.netlify.app/',
    skills: ['JavaScript'],
    imagePath: '/img/portfolio/forkify.png',
    alt: 'Recipe searching app',
  },
  {
    id: 6,
    opusNumber: '',
    siteName: 'Mapty',
    subtitle: 'excercise logging app',
    aboutText: 'This was one of my first times working with external libraries',
    cardText:
      'An exercise-logging app that stores data locally on your computer and is easy to use.',
    href: 'https://mapty-portfolio-app.netlify.app/',
    skills: ['JavaScript'],
    imagePath: '/img/portfolio/mapty.png',
    alt: 'Map-based exercise logging app',
  },
  {
    id: 5,
    opusNumber: '',
    siteName: 'Bankist: Login Page',
    subtitle: 'minimalist banking app',
    aboutText: 'I love the design on this one...',
    cardText:
      'A beautiful landing page for a banking app built using pure JavaScript.',
    href: 'https://bankist-app-morgan-oshaughnessey.netlify.app/',
    skills: ['JavaScript'],
    imagePath: '/img/portfolio/bankist-login.png',
    alt: 'Landing page for a minimalist-themed bank',
  },
  {
    id: 4,
    opusNumber: '',
    siteName: 'Bankist: App',
    subtitle: 'minimalist banking app',
    aboutText: "The immortal words: 'what is cick'",
    cardText:
      'A deep study in array methods from an amazing course by Jonas Schmedtmann',
    href: 'https://bankist-login-morgan-oshaughnessey.netlify.app',
    skills: ['JavaScript'],
    imagePath: '/img/portfolio/bankist-app.png',
    alt: 'Minimalist banking app, white background with green, yellow, and red interface to complete financial transations.',
  },
  {
    id: 3,
    opusNumber: '',
    siteName: 'Pig Game',
    subtitle: 'Dice-rolling game',
    aboutText: 'This is still a fun game to play!',
    cardText: 'A 2-player dice-rolling game, built with pure Javscript!',
    href: 'https://pig-game-morgan-oshaughnessey.netlify.app/',
    skills: ['JavaScript'],
    imagePath: '/img/portfolio/pig-game.png',
    alt: 'Dice rolling game, styled in pink and red, first player to 100 wins.',
  },
  {
    id: 2,
    opusNumber: '',
    siteName: 'Guess My Number',
    subtitle: 'Number guessing game',
    aboutText:
      'Lol I remember sending this one to all my friends and they were very impressed! The dancing bird came from afterward, when Cali was showing off some advanced css.',
    cardText:
      'An early class project, lots of interesting logic behind the scenes!',
    href: 'https://guess-my-number-morgan-oshaughnessey.netlify.app/',
    skills: ['JavaScript'],
    imagePath: '/img/portfolio/guess-my-number.png',
    alt: 'number-guessing app',
  },
  {
    id: 1,
    opusNumber: '',
    siteName: 'Music Player',
    subtitle: 'A platform for my musical compositions',
    aboutText:
      '"Ok, so, this is REALLY cool but...what is a boullion, what is a div?"',
    cardText:
      'My very first app! A platform for my musical compositions. Built with loving and patient help from my girlfriend.',
    href: 'https://moshalto.com/',
    skills: ['JavaScript', 'React'],
    imagePath: '/img/portfolio/music-player.png',
    alt: 'moshalto.com website image, a music player styled to look like a rubiks cube',
  },
];
